const CenterItems=()=>{
return (
<nav class="b2canga-header-0-x-menu">
							<ul class="b2canga-header-0-x-menu--list">
								<li
									class="b2canga-header-0-x-menu--item"
									data-url="/mujer"
								>
									<a
										class="b2canga-header-0-x-menu--link"
										href="/mujer"
										target="_self"
									>
										damas
									</a>
								</li>
								<li
									class="b2canga-header-0-x-menu--item"
									data-url="/hombre"
								>
									<a
										class="b2canga-header-0-x-menu--link"
										href="/hombre"
										target="_self"
									>
										caballeros
									</a>
								</li>
								
								<li
									class="b2canga-header-0-x-menu--item"
									data-url="/cosas"
								>
									<a
										class="b2canga-header-0-x-menu--link"
										href="/kids"
										target="_self"
									>
										kids
									</a>
								</li>
								<li
									class="b2canga-header-0-x-menu--item"
									data-url="/cosas"
								>
									<a
										class="b2canga-header-0-x-menu--link"
										href="/cosas"
										target="_self"
									>
										accesorio 
									</a>
								</li>
								<li
									class="b2canga-header-0-x-menu--item"
									data-url="/tiendas"
								>
									<a
										class="b2canga-header-0-x-menu--link"
										href="/tiendas"
										target="_self"
									>
										tiendas
									</a>
								</li>
							{/* 	<li
									class="b2canga-header-0-x-menu--item"
									data-url="https://comunidad.anga.net/activismo"
								>
									<a
										class="b2canga-header-0-x-menu--link"
										href="https://comunidad.anga.net/activismo"
										target="_blank"
										rel="noopener"
									>
										activismo
									</a>
								</li>*/}
								<li
									data-url="/sale"
									class="b2canga-header-0-x-menu--item"
								>
									<a
										class="b2canga-header-0-x-menu--link"
										href="/sale"
										style={{backgroundColor: "gold"}}
									>
										SALE
									</a>
								</li>
							</ul>
						</nav>
);
};
export default CenterItems;