const CenterItems=()=>{
return (
<nav class="b2cmattelsa-header-0-x-menu">
							<ul class="b2cmattelsa-header-0-x-menu--list">
								<li
									class="b2cmattelsa-header-0-x-menu--item"
									data-url="/hombre"
								>
									<a
										class="b2cmattelsa-header-0-x-menu--link"
										href="/hombre"
										target="_self"
									>
										hombre
									</a>
								</li>
								<li
									class="b2cmattelsa-header-0-x-menu--item"
									data-url="/mujer"
								>
									<a
										class="b2cmattelsa-header-0-x-menu--link"
										href="/mujer"
										target="_self"
									>
										mujer
									</a>
								</li>
								<li
									class="b2cmattelsa-header-0-x-menu--item"
									data-url="/cosas"
								>
									<a
										class="b2cmattelsa-header-0-x-menu--link"
										href="/cosas"
										target="_self"
									>
										cosas
									</a>
								</li>
								<li
									class="b2cmattelsa-header-0-x-menu--item"
									data-url="/tiendas"
								>
									<a
										class="b2cmattelsa-header-0-x-menu--link"
										href="/tiendas"
										target="_self"
									>
										tiendas
									</a>
								</li>
								<li
									class="b2cmattelsa-header-0-x-menu--item"
									data-url="https://comunidad.mattelsa.net/activismo"
								>
									<a
										class="b2cmattelsa-header-0-x-menu--link"
										href="https://comunidad.mattelsa.net/activismo"
										target="_blank"
										rel="noopener"
									>
										activismo
									</a>
								</li>
								<li
									data-url="/sale"
									class="b2cmattelsa-header-0-x-menu--item"
								>
									<a
										class="b2cmattelsa-header-0-x-menu--link"
										href="/sale"
										style={{backgroundColor: "gold"}}
									>
										SALE
									</a>
								</li>
							</ul>
						</nav>
);
};
export default CenterItems;