export const API = "API";

//cotizaciones
export const LIST_QUOTES = "LIST_QUOTES";
export const GET_ALL_QUOTES = "GET_ALL_QUOTES";
export const GET_QUOTES_SEPARATED = "GET_QUOTES_SEPARATED";
export const UPDATE_QUOTE = "UPDATE_QUOTE";
export const RESET_QUOTE = "RESET_QUOTE";
///finCotizaciones

//recaudo directo
export const GET_ALL_DIRECT_COLLECTION = "GET_ALL_DIRECT_COLLECTION";
export const ADD_DIRECT_COLLECTION = "ADD_DIRECT_COLLECTION";
export const UPDATE_DIRECT_COLLECTION = "UPDATE_DIRECT_COLLECTION";
export const ADD_VERIFICATION_DIRECT_COLLECTION =
	"ADD_VERIFICATION_DIRECT_COLLECTION";
export const UPDATE_CHECK_DIRECT_COLLECTION = "UPDATE_CHECK_DIRECT_COLLECTION";
export const SEND_DIRECT_COLLECTION = "SEND_DIRECT_COLLECTION";
//Fin recaudo directo

//recaudo fiducia
export const GET_ALL_TRUST_COLLECTION = "GET_ALL_TRUST_COLLECTION";
export const ADD_TRUST_COLLECTION = "ADD_TRUST_COLLECTION";
export const UPDATE_TRUST_COLLECTION = "UPDATE_TRUST_COLLECTION";
export const LAST_PAYMENT_FIDUCIARY = "LAST_PAYMENT_FIDUCIARY";
//recaudo fiducia

export const SET_USER_INFO = "SET_USER_INFO";
export const RESET_USER_INFO = "RESET_USER_INFO";
export const TOGGLE_LOADER = "TOGGLE_LOADER";
export const SET_USER_PERMISSIONS = "SET_USER_PERMISSIONS";

export const SET_ALL_USERS = "SET_ALL_USERS";
export const GET_AVALIABLE_USERS = "GET_AVALIABLE_USERS";
export const ADD_USER = "ADD_USER";
export const REMOVE_USER = "REMOVE_USER";
export const UPDATE_USER = "UPDATE_USER";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const UPDATE_STATE_USER = "UPDATE_STATE_USER";
export const GET_MODULES_USER = "GET_SUBMODULES_USER";

export const SET_ALL_AFFILIATED_COMPANY = "SET_ALL_AFFILIATED_COMPANY";
export const ADD_AFFILIATED_COMPANY = "ADD_AFFILIATED_COMPANY";
export const REMOVE_AFFILIATED_COMPANY = "REMOVE_AFFILIATED_COMPANY";
export const UPDATE_AFFILIATED_COMPANY = "UPDATE_AFFILIATED_COMPANY";
export const RESET_AFFILIATED_COMPANY = "RESET_AFFILIATED_COMPANY";
export const UPDATE_STATE_AFFILIATED_COMPANY =
	"UPDATE_STATE_AFFILIATED_COMPANY";
	export const SET_ALL_CONSIGNMENT_CONCEPT = "SET_ALL_CONSIGNMENT_CONCEPT";
	export const ADD_CONSIGNMENT_CONCEPT = "ADD_CONSIGNMENT_CONCEPT";
	export const REMOVE_CONSIGNMENT_CONCEPT = "REMOVE_CONSIGNMENT_CONCEPT";
	export const UPDATE_CONSIGNMENT_CONCEPT = "UPDATE_CONSIGNMENT_CONCEPT";
	export const RESET_CONSIGNMENT_CONCEPT = "RESET_CONSIGNMENT_CONCEPT";
	export const UPDATE_STATE_CONSIGNMENT_CONCEPT =
		"UPDATE_STATE_CONSIGNMENT_CONCEPT";
	
	export const SET_ALL_PROJECTS_CLASSIFICATION = "SET_ALL_PROJECTS_CLASSIFICATION";
	export const ADD_PROJECTS_CLASSIFICATION = "ADD_PROJECTS_CLASSIFICATION";
	export const REMOVE_PROJECTS_CLASSIFICATION = "REMOVE_PROJECTS_CLASSIFICATION";
	export const UPDATE_PROJECTS_CLASSIFICATION = "UPDATE_PROJECTS_CLASSIFICATION";
	export const RESET_PROJECTS_CLASSIFICATION = "RESET_PROJECTS_CLASSIFICATION";
	export const UPDATE_STATE_PROJECTS_CLASSIFICATION =
		"UPDATE_STATE_PROJECTS_CLASSIFICATION";
	
export const SET_ALL_ACTIVITY_TYPE = "SET_ALL_ACTIVITY_TYPE";
export const ADD_ACTIVITY_TYPE = "ADD_ACTIVITY_TYPE";
export const REMOVE_ACTIVITY_TYPE = "REMOVE_ACTIVITY_TYPE";
export const UPDATE_ACTIVITY_TYPE = "UPDATE_ACTIVITY_TYPE";
export const UPDATE_STATE_ACTIVITY_TYPE = "UPDATE_STATE_ACTIVITY_TYPE";
export const RESET_ACTIVITY_TYPE = "RESET_ACTIVITY_TYPE";

export const SET_ALL_CHANNEL = "SET_ALL_CHANNEL";
export const ADD_CHANNEL = "ADD_CHANNEL";
export const REMOVE_CHANNEL = "REMOVE_CHANNEL";
export const UPDATE_CHANNEL = "UPDATE_CHANNEL";
export const RESET_CHANNEL = "RESET_CHANNEL";
export const UPDATE_STATE_CHANNEL = "UPDATE_STATE_CHANNEL";

export const SET_ALL_ATTENTION_PLACES = "SET_ALL_ATTENTION_PLACES";
export const ADD_ATTENTION_PLACES = "ADD_ATTENTION_PLACES";
export const REMOVE_ATTENTION_PLACES = "REMOVE_ATTENTION_PLACES";
export const UPDATE_ATTENTION_PLACES = "UPDATE_ATTENTION_PLACES";
export const RESET_ATTENTION_PLACES = "RESET_ATTENTION_PLACES";
export const UPDATE_STATE_ATTENTION_PLACES = "UPDATE_STATE_ATTENTION_PLACES";

export const SET_ALL_OCCUPATION = "SET_ALL_OCCUPATION";
export const ADD_OCCUPATION = "ADD_OCCUPATION";
export const REMOVE_OCCUPATION = "REMOVE_OCCUPATION";
export const UPDATE_OCCUPATION = "UPDATE_OCCUPATION";
export const RESET_OCCUPATION = "RESET_OCCUPATION";

export const UPDATE_STATE_OCCUPATION = "UPDATE_STATE_OCCUPATION";

export const SET_ALL_PROFILE = "SET_ALL_PROFILE";
export const ADD_PROFILE = "ADD_PROFILE";
export const REMOVE_PROFILE = "REMOVE_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const RESET_PROFILE = "RESET_PROFILE";
export const UPDATE_STATE_PROFILE = "UPDATE_STATE_PROFILE";

export const SET_ALL_REGISTER_TYPE = "SET_ALL_REGISTER_TYPE";
export const ADD_REGISTER_TYPE = "ADD_REGISTER_TYPE";
export const REMOVE_REGISTER_TYPE = "REMOVE_REGISTER_TYPE";
export const UPDATE_REGISTER_TYPE = "UPDATE_REGISTER_TYPE";
export const RESET_REGISTER_TYPE = "RESET_REGISTER_TYPE";
export const UPDATE_STATE_REGISTER_TYPE = "UPDATE_STATE_REGISTER_TYPE";

export const SET_ALL_ADVERTISING_IMAGE = "SET_ALL_ADVERTISING_IMAGE";
export const ADD_ADVERTISING_IMAGE = "ADD_ADVERTISING_IMAGE";
export const REMOVE_ADVERTISING_IMAGE = "REMOVE_ADVERTISING_IMAGE";
export const UPDATE_ADVERTISING_IMAGE = "UPDATE_ADVERTISING_IMAGE";
export const RESET_ADVERTISING_IMAGE = "RESET_ADVERTISING_IMAGE";
export const UPDATE_STATE_ADVERTISING_IMAGE = "UPDATE_STATE_ADVERTISING_IMAGE";

export const SET_ALL_ASSESSOR = "SET_ALL_ASSESSOR";
export const ADD_ASSESSOR = "ADD_ASSESSOR";
export const ASSESOR_REPORT = "ASSESOR_REPORT";
export const REMOVE_ASSESSOR = "REMOVE_ASSESSOR";
export const UPDATE_ASSESSOR = "UPDATE_ASSESSOR";
export const RESET_ASSESSOR = "RESET_ASSESSOR";
export const UPDATE_STATE_ADVISER = "UPDATE_STATE_ADVISER";

export const SET_ALL_AUDITS_TYPE = "SET_ALL_AUDITS_TYPE";
export const ADD_AUDITS_TYPE = "ADD_AUDITS_TYPE";
export const REMOVE_AUDITS_TYPE = "REMOVE_AUDITS_TYPE";
export const UPDATE_AUDITS_TYPE = "UPDATE_AUDITS_TYPE";
export const RESET_AUDITS_TYPE = "RESET_AUDITS_TYPE";

export const SET_ALL_CAUGHT_ERROR = "SET_ALL_CAUGHT_ERROR";
export const ADD_CAUGHT_ERROR = "ADD_CAUGHT_ERROR";
export const REMOVE_CAUGHT_ERROR = "REMOVE_CAUGHT_ERROR";
export const UPDATE_CAUGHT_ERROR = "UPDATE_CAUGHT_ERROR";
export const RESET_CAUGHT_ERROR = "RESET_CAUGHT_ERROR";

export const SET_ALL_GENERAL_ACTIVITY = "SET_ALL_GENERAL_ACTIVITY";
export const ADD_GENERAL_ACTIVITY = "ADD_GENERAL_ACTIVITY";
export const REMOVE_GENERAL_ACTIVITY = "REMOVE_GENERAL_ACTIVITY";
export const UPDATE_GENERAL_ACTIVITY = "UPDATE_GENERAL_ACTIVITY";
export const END_GENERAL_ACTIVITY = "END_GENERAL_ACTIVITY";
export const RESET_GENERAL_ACTIVITY = "RESET_GENERAL_ACTIVITY";

export const SET_ALL_GENERAL_SETTING = "SET_ALL_GENERAL_SETTING";
export const ADD_GENERAL_SETTING = "ADD_GENERAL_SETTING";
export const REMOVE_GENERAL_SETTING = "REMOVE_GENERAL_SETTING";
export const UPDATE_GENERAL_SETTING = "UPDATE_GENERAL_SETTING";
export const RESET_GENERAL_SETTING = "RESET_GENERAL_SETTING";

export const SET_ALL_MODULE = "SET_ALL_SUBMODULE";
export const ADD_MODULE = "ADD_SUBMODULE";
export const REMOVE_MODULE = "REMOVE_SUBMODULE";
export const UPDATE_MODULE = "UPDATE_SUBMODULE";
export const RESET_MODULE = "RESET_SUBMODULE";
export const UPDATE_STATE_MODULE = "UPDATE_STATE_SUBMODULE";

export const SET_ALL_PERMISSION = "SET_ALL_PERMISSION";
export const ADD_PERMISSION = "ADD_PERMISSION";
export const REMOVE_PERMISSION = "REMOVE_PERMISSION";
export const UPDATE_PERMISSION = "UPDATE_PERMISSION";
export const RESET_PERMISSION = "RESET_PERMISSION";
export const SET_PERMISSION_BY_PROFILE = "SET_PERMISSION_BY_PROFILE";
export const SET_SAVE_PERMISSIONS_BY_PROFILE =
	"SET_SAVE_PERMISSIONS_BY_PROFILE";

export const SET_ALL_PRICES_RANGE = "SET_ALL_PRICES_RANGE";
export const SET_ALL_PRICES_RANGE_ACTIVATED = "SET_ALL_PRICES_RANGE_ACTIVATED";
export const ADD_PRICES_RANGE = "ADD_PRICES_RANGE";
export const REMOVE_PRICES_RANGE = "REMOVE_PRICES_RANGE";
export const UPDATE_PRICES_RANGE = "UPDATE_PRICES_RANGE";
export const RESET_PRICES_RANGE = "RESET_PRICES_RANGE";

export const SET_ALL_RESOURCE = "SET_ALL_RESOURCE";
export const ADD_RESOURCE = "ADD_RESOURCE";
export const REMOVE_RESOURCE = "REMOVE_RESOURCE";
export const UPDATE_RESOURCE = "UPDATE_RESOURCE";
export const RESET_RESOURCE = "RESET_RESOURCE";

export const SET_ALL_SYSTEM_AUDIT = "SET_ALL_SYSTEM_AUDIT";
export const ADD_SYSTEM_AUDIT = "ADD_SYSTEM_AUDIT";
export const REMOVE_SYSTEM_AUDIT = "REMOVE_SYSTEM_AUDIT";
export const UPDATE_SYSTEM_AUDIT = "UPDATE_SYSTEM_AUDIT";
export const RESET_SYSTEM_AUDIT = "RESET_SYSTEM_AUDIT";
export const RUTA = process.env.REACT_APP_RUTA;
export const RUTA_API = process.env.REACT_APP_API_URL;
export const RUTA_FORMAT_FIDUCIARY = RUTA_API + process.env.REACT_APP_RUTA_FORMAT_FIDUCIARY;
export const RUTA_FORMAT_PAYMENT_FIDUCIARY = RUTA_API + process.env.REACT_APP_RUTA_FORMAT_PAYMENT_FIDUCIARY;
export const RUTA_API_MULTIMEDIA = RUTA_API + RUTA + process.env.REACT_APP_RUTA_API_MULTIMEDIA;
export const VALID_DOCUMENT_UPLOAD = process.env.REACT_APP_VALID_DOCUMENT_UPLOAD;
export const TOKEN = `{ 'Authorization':Storage.getToken() }`;


//proyectos
export const SET_ALL_PROJECTS = "SET_ALL_PROJECTS";
export const ADD_PROJECT = "ADD_PROJECT";
export const ADD_ATTACHMENT = "ADD_ATTACHMENT";
export const REMOVE_PROJECT = "REMOVE_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const RESET_PROJECT = "RESET_PROJECT";
export const GET_BY_PROJECTS = "GET_BY_PROJECTS";

//direc

export const GET_UNIT_BY_PROJECT_ID = "GET_UNIT_BY_PROJECT_ID";
export const UPDATE_UNIT_BY_PROJECT_ID = "UPDATE_UNIT_BY_PROJECT_ID";
export const RESET_UNIT_BY_PROJECT_ID = "RESET_UNIT_BY_PROJECT_ID";
export const REMOVE_UNIT="REMOVE_UNIT";

export const SET_ALL_PAYMENT_RELATIONSHIP_SETTING =
	"SET_ALL_PAYMENT_RELATIONSHIP_SETTING";
export const ADD_PAYMENT_RELATIONSHIP_SETTING =
	"ADD_PAYMENT_RELATIONSHIP_SETTING";
export const RESET_PAYMENT_RELATIONSHIP_SETTING =
	"RESET_PAYMENT_RELATIONSHIP_SETTING";

export const SET_ALL_CONTROL_POWERS = "SET_ALL_CONTROL_POWERS";
export const ADD_CONTROL_POWER = "ADD_CONTROL_POWER";
export const REMOVE_CONTROL_POWER = "REMOVE_CONTROL_POWER";
export const UPDATE_CONTROL_POWER = "UPDATE_CONTROL_POWER";
export const RESET_CONTROL_POWER = "RESET_CONTROL_POWER";

export const ADD_UNIT_TYPE = "ADD_UNIT_TYPE";
export const DUPLICATE_UNIT_TYPE = "DUPLICATE_UNIT_TYPE";
export const REMOVE_UNIT_TYPE = "REMOVE_UNIT_TYPE";
export const UPDATE_UNIT_TYPE = "UPDATE_UNIT_TYPE";
export const SET_ALL_UNIT_TYPE = "SET_ALL_UNIT_TYPE";
export const REMOVE_ATTACHMENT = "REMOVE_ATTACHMENT";
export const RESET_UNIT_TYPE = "RESET_UNIT_TYPE";

export const UPDATE_OR_CREATE_SALES_PARAMETERS = "UPDATE_OR_CREATE_SALES_PARAMETERS";
export const GET_SALE_PARAMETER_BY_ID = "GET_SALE_PARAMETER_BY_ID";
export const RESET_SALE_PARAMETER = "RESET_SALE_PARAMETER";

export const ADD_BUILDER = "ADD_BUILDER";
export const SET_ALL_BUILDER = "SET_ALL_BUILDER";

export const UPDATE_OR_CREATE_INCREASE_POLICY =
	"UPDATE_OR_CREATE_INCREASE_POLICY";
export const SET_ALL_INCREASE_POLICY = "SET_ALL_INCREASE_POLICY";
export const REMOVE_INCREASE_POLICY = "REMOVE_INCREASE_POLICY";
export const RESET_INCREASE_POLICY = "RESET_INCREASE_POLICY";

export const UPDATE_OR_CREATE_DISCOUNT_POLICY =
	"UPDATE_OR_CREATE_DISCOUNT_POLICY";
export const SET_ALL_DISCOUNT_POLICY = "SET_ALL_DISCOUNT_POLICY";
export const REMOVE_DISCOUNT_POLICY = "REMOVE_DISCOUNT_POLICY";
export const RESET_DISCOUNT_POLICY = "RESET_DISCOUNT_POLICY";

export const UPDATE_OR_CREATE_ASSIGNED_TECHNICIAN =
	"UPDATE_OR_CREATE_ASSIGNED_TECHNICIAN";
export const SET_ALL_ASSIGNED_TECHNICIAN = "SET_ALL_ASSIGNED_TECHNICIAN";
export const REMOVE_ASSIGNED_TECHNICIAN = "REMOVE_ASSIGNED_TECHNICIAN";
export const RESET_ASSIGNED_TECHNICIAN = "RESET_ASSIGNED_TECHNICIAN";

export const UPDATE_OR_CREATE_ASSIGNED_COUNTERS =
	"UPDATE_OR_CREATE_ASSIGNED_COUNTERS";
export const SET_ALL_ASSIGNED_COUNTERS = "SET_ALL_ASSIGNED_COUNTERS";
export const REMOVE_ASSIGNED_COUNTERS = "REMOVE_ASSIGNED_COUNTERS";
export const RESET_ASSIGNED_COUNTERS = "RESET_ASSIGNED_COUNTERS";

export const UPDATE_OR_CREATE_ASSIGNED_SITE_DIRECTORS =
	"UPDATE_OR_CREATE_ASSIGNED_SITE_DIRECTORS";
export const SET_ALL_ASSIGNED_SITE_DIRECTORS =
	"SET_ALL_ASSIGNED_SITE_DIRECTORS";
export const REMOVE_ASSIGNED_SITE_DIRECTORS = "REMOVE_ASSIGNED_SITE_DIRECTORS";
export const RESET_ASSIGNED_SITE_DIRECTORS = "RESET_ASSIGNED_SITE_DIRECTORS";

export const UPDATE_OR_CREATE_SALE_LEGALIZATION =
	"UPDATE_OR_CREATE_SALE_LEGALIZATION";
export const SET_ALL_SALE_LEGALIZATION = "SET_ALL_SALE_LEGALIZATION";
export const REMOVE_SALE_LEGALIZATION = "REMOVE_SALE_LEGALIZATION";
export const RESET_SALE_LEGALIZATION = "RESET_SALE_LEGALIZATION";

export const FETCH_ALL_POLICY_TO_COMPLY = "FETCH_ALL_POLICY_TO_COMPLY";
export const RESET_ALL_POLICY_TO_COMPLY = "RESET_ALL_POLICY_TO_COMPLY";

export const UPDATE_OR_CREATE_COMMISSION_PARAMETER =
	"UPDATE_OR_CREATE_COMMISSION_PARAMETER";
export const FETCH_ALL_COMMISSION_PARAMETER = "FETCH_ALL_COMMISSION_PARAMETER";
export const REMOVE_COMMISSION_PARAMETER = "REMOVE_COMMISSION_PARAMETER";
export const RESET_COMMISSION_PARAMETER = "RESET_COMMISSION_PARAMETER";

export const GET_OPTION_SELECT = "GET_OPTION_SELECT";

//clientes
export const SET_ALL_CUSTOMER = "SET_ALL_CUSTOMER";
export const SET_CUSTOMER_UNITS = "SET_CUSTOMER_UNITS";
export const ADD_CUSTOMER = "ADD_CUSTOMER";
export const REMOVE_CUSTOMER = "REMOVE_CUSTOMER";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const UPDATE_STATE_CUSTOMER = "UPDATE_STATE_CUSTOMER";
export const RESET_CUSTOMER = "RESET_CUSTOMER";
export const SET_CUSTOMER_BY_ID = "SET_CUSTOMER_BY_ID";
export const REASSIGNMENT_ASESSOR_CUSTOMER = "REASSIGNMENT_ASESSOR_CUSTOMER";

//actividadClientes
export const SET_ALL_CUSTOMER_ACTIVITY = "SET_ALL_CUSTOMER_ACTIVITY";
export const ADD_CUSTOMER_ACTIVITY = "ADD_CUSTOMER_ACTIVITY";
export const UPDATE_CUSTOMER_ACTIVITY = "UPDATE_CUSTOMER_ACTIVITY";

//interesClientes
export const UPDATE_CUSTOMER_INTEREST = "UPDATE_CUSTOMER_INTEREST";

//Coutas

export const UPDATE_QUOTE_SEPARATION = "UPDATE_QUOTE_SEPARATION";
export const UPDATE_QUOTE_LEGALIZATION_SALE = "UPDATE_QUOTE_LEGALIZATION_SALE";
export const GET_QUOTATION_BY_ID = "GET_QUOTATION_BY_ID";

//Cupones
export const ADD_COUPON = "ADD_COUPON";
export const UPDATE_COUPON = "UPDATE_COUPON";
export const DOWNLOAD_COUPON = "DOWNLOAD_COUPON";
export const GET_ALL_COUPON = "GET_ALL_COUPON";
export const GET_CODE_COUPON = "GET_CODE_COUPON";
export const DELETE_COUPON = "DELETE_COUPON";

//Ventas relizadaas
export const SET_ALL_SALE_MADE = "SET_ALL_SALE_MADE";
export const DATA_SALE_UPDATE = "DATA_SALE_UPDATE";
//Escrituracion
export const ADD_DEED = "ADD_DEED";
export const UPDATE_DEED = "UPDATE_DEED";
export const GET_DEED_BY_ID = "GET_DEED_BY_ID";
//Ventas realizadas - Legalizar documentos
export const SET_ALL_LEGALIZE_DOCUMENTS = "SET_ALL_LEGALIZE_DOCUMENTS";
export const UPLOAD_LEGALIZE_DOCUMENT = "UPLOAD_LEGALIZE_DOCUMENT";
export const RESET_LEGALIZE_DOCUMENTS = "RESET_LEGALIZE_DOCUMENTS";
export const UPDATE_PERCENTAGE_LEGALIZED_DOCUMENTS =
	"UPDATE_PERCENTAGE_LEGALIZED_DOCUMENTS";

//Ventas realizadas - Asignar responsables
export const SET_ALL_ASSIGN_RESPONSIBLE = "SET_ALL_ASSIGN_RESPONSIBLE";
export const UPDATE_OR_CREATE_ASSIGN_RESPOSIBLE =
	"UPDATE_OR_CREATE_ASSIGN_RESPOSIBLE";

//Ventas realizadas - Forma de pago restante
export const SET_ALL_REMAINING_PAYMENT_METHOD =
	"SET_ALL_REMAINING_PAYMENT_METHOD";
export const CREATE_REMAINING_PAYMENT_METHOD =
	"CREATE_REMAINING_PAYMENT_METHOD";
export const RESET_REMAINING_PAYMENT_METHOD = "RESET_REMAINING_PAYMENT_METHOD";

//Ventas realizadas - Cambiar cliente
export const CHANGE_CUSTOMER = "CHANGE_CUSTOMER";

//Ventas realizadas - Administrar Canje
export const SET_ALL_EXCHANGES = "SET_ALL_EXCHANGES";
export const APPLY_EXCHANGE = "APPLY_EXCHANGE";
export const UPDATE_SALE = "UPDATE_SALE";

//Ventas realizadas - Desistimiento
export const CREATE_SALE_WITHDRAWAL = "CREATE_SALE_WITHDRAWAL";
export const FETCH_BY_ID_SALE_WITHDRAWAL = "FETCH_SALE_WITHDRAWAL";
export const UPDATE_SALE_WITHDRAWAL = "UPDATE_SALE_WITHDRAWAL";
export const RESET_SALE_WITHDRAWAL = "RESET_SALE_WITHDRAWAL";

export const RESET_ASSIGN_RESPONSIBLE = "RESET_ASSIGN_RESPONSIBLE";

export const START_FETCHING_ALL_REFORM_REQUEST = "START_FETCHING_ALL_REFORM_REQUEST";
export const GET_ALL_REFORM_REQUEST = "GET_ALL_REFORM_REQUEST";
export const ERROR_FETCHING_ALL_REFORM_REQUEST = "ERROR_FETCHING_ALL_REFORM_REQUEST";

export const START_FETCHING_ALL_SALES_WHIT_REFORM_REQUEST = "START_FETCHING_ALL_SALES_WHIT_REFORM_REQUEST";
export const GET_ALL_SALES_WHIT_REFORM_REQUEST = "GET_ALL_SALES_WHIT_REFORM_REQUEST";

export const START_ADD_REFORM_REQUEST = "START_ADD_REFORM_REQUEST";
export const ADD_REFORM_REQUEST = "ADD_REFORM_REQUEST";
export const ERROR_ADD_REFORM_REQUEST = "ERROR_ADD_REFORM_REQUEST";

export const START_REMOVE_REFORM_REQUEST = "START_REMOVE_REFORM_REQUEST";
export const REMOVE_REFORM_REQUEST = "REMOVE_REFORM_REQUEST";
export const ERROR_REMOVE_REFORM_REQUEST = "ERROR_REMOVE_REFORM_REQUEST";

export const START_UPDATE_REFORM_REQUEST = "START_UPDATE_REFORM_REQUEST";
export const UPDATE_REFORM_REQUEST = "UPDATE_REFORM_REQUEST";
export const ERROR_UPDATE_REFORM_REQUEST = "ERROR_UPDATE_REFORM_REQUEST";
export const CLEAR_STATE_REFORM_REQUEST = "CLEAR_STATE_REFORM_REQUEST";

//postSales
export const START_FETCHING_ALL_POS_SALE = "START_FETCHING_ALL_POS_SALE";
export const GET_ALL_POS_SALE = "GET_ALL_POS_SALE";
export const ERROR_FETCHING_ALL_POS_SALE = "ERROR_FETCHING_ALL_POS_SALE";

export const START_FETCHING_ALL_POS_SALE_BY_SALE_ID = "START_FETCHING_ALL_POS_SALE_BY_SALE_ID";
export const GET_ALL_POS_SALE_BY_SALE_ID = "GET_ALL_POS_SALE_BY_SALE_ID";
export const ERROR_FETCHING_ALL_POS_SALE_BY_SALE_ID = "ERROR_FETCHING_ALL_POS_SALE_BY_SALE_ID";

export const START_ADD_POS_SALE = "START_ADD_POS_SALE";
export const ADD_POS_SALE = "ADD_POS_SALE";
export const ERROR_ADD_POS_SALE = "ERROR_ADD_POS_SALE";

export const START_REMOVE_POS_SALE = "START_REMOVE_POS_SALE";
export const REMOVE_POS_SALE = "REMOVE_POS_SALE";
export const ERROR_REMOVE_POS_SALE = "ERROR_REMOVE_POS_SALE";

export const START_UPDATE_POS_SALE = "START_UPDATE_POS_SALE";
export const UPDATE_POS_SALE = "UPDATE_POS_SALE";
export const ERROR_UPDATE_POS_SALE = "ERROR_UPDATE_POS_SALE";
export const CLEAR_ALL_STATE_POS_SALE = "CLEAR_ALL_STATE_POS_SALE";
export const CLEAR_STATE_POS_SALE_BY_SALE = "CLEAR_STATE_POS_SALE_BY_SALE";

//Informe Competencias
export const GET_COMPETING_PROJECTS = "GET_COMPETING_PROJECTS";
export const GET_REPORT_COMPETING = "GET_REPORT_COMPETING";

//Informe ClientePotenciales
export const GET_POTENTIAL_CUSTOMERS = "GET_POTENTIAL_CUSTOMERS";

//Informe comissiones
export const GET_COMISSIONS = "GET_COMISSIONS";
//auditoria
export const GET_AUDITS = "GET_AUDITS";
//Informe Estado de cuenta
export const GET_ACCOUNT_STATUS = "GET_ACCOUNT_STATUS";

//Estado Proyectos
export const SET_STATES_PROJECTS = "SET_STATES_PROJECTS";

//Formater number
export const FORMATTER_INPUT_NUMBER = {
	formatter: (value) => `$ ${value}`.replace(/\B(?=(\d{3})+(?!\d))/g, ","),
};
export const GET_REQUEST_REFORMS_REPORT = "GET_REQUEST_REFORMS_REPORT";
export const GET_GENERAL_COMMERCIAL_MANAGEMENT_REPORT = "GET_GENERAL_COMMERCIAL_MANAGEMENT_REPORT";
export const GET_SALES_REPORT = "GET_SALES_REPORT";

export const FORMATTER_PESO = new Intl.NumberFormat("es-CO", {
	style: "currency",
	currency: "COP",
	minimumFractionDigits: 0,
});

export const GET_STATUS_REQUEST_REFORMS = "GET_STATUS_REQUEST_REFORMS";
export const GET_EXCEL_REQUEST_REFORMS_REPORT = "GET_EXCEL_REQUEST_REFORMS_REPORT";

export const GET_EXCEL_POTENTIAL_CLIENTS_DATABASE = "GET_EXCEL_POTENTIAL_CLIENTS_DATABASE";

// --Permisos
// Permisos - perfiles
export const SHOW_PROFILES_PERMISSION = 8;
export const CREATE_PROFILE_PERMISSION = 7;
export const UPDATE_PROFILE_PERMISSION = 6;
export const DELETE_PROFILE_PERMISSION = 5;
export const GRANT_PROFILE_PERMISSION = 4;

// Permisos - usuarios
export const SHOW_USERS_PERMISSION = 9;
export const CREATE_USER_PERMISSION = 11;
export const UPDATE_USER_PERMISSION = 12;
export const DELETE_USER_PERMISSION = 10;

// Permisos - asesor
export const SHOW_ADVISORS_PERMISSION = 13;
export const CREATE_ADVISOR_PERMISSION = 14;
export const UPDATE_ADVISOR_PERMISSION = 15;
export const DELETE_ADVISOR_PERMISSION = 16;

// Permisos - actividades generales
export const SHOW_GENERAL_ACTIVITIES_PERMISSION = 17;
export const CREATE_GENERAL_ACTIVITY_PERMISSION = 18;
export const UPDATE_GENERAL_ACTIVITY_PERMISSION = 19;
export const DELETE_GENERAL_ACTIVITY_PERMISSION = 20;

// Permisos - empresas asociadas
export const SHOW_AFFILIATES_PERMISSION = 21;
export const CREATE_AFFILIATE_PERMISSION = 22;
export const UPDATE_AFFILIATE_PERMISSION = 23;
export const DELETE_AFFILIATE_PERMISSION = 24;

// Permisos - lugares de atención
export const SHOW_ATTENTION_PLACES_PERMISSION = 25;
export const CREATE_ATTENTION_PLACE_PERMISSION = 26;
export const UPDATE_ATTENTION_PLACE_PERMISSION = 27;
export const DELETE_ATTENTION_PLACE_PERMISSION = 28;

// Permisos - ¿Cómo se enteró?
export const SHOW_CHANNELS_PERMISSION = 29;
export const CREATE_CHANNEL_PERMISSION = 30;
export const UPDATE_CHANNEL_PERMISSION = 31;
export const DELETE_CHANNEL_PERMISSION = 32;

// Permisos - tipo de registro
export const SHOW_RECORD_TYPES_PERMISSION = 33;
export const CREATE_RECORD_TYPE_PERMISSION = 34;
export const UPDATE_RECORD_TYPE_PERMISSION = 35;
export const DELETE_RECORD_TYPE_PERMISSION = 36;

// Permisos - tipo de actividad
export const SHOW_ACTIVITY_TYPES_PERMISSION = 37;
export const CREATE_ACTIVITY_TYPE_PERMISSION = 38;
export const UPDATE_ACTIVITY_TYPE_PERMISSION = 39;
export const DELETE_ACTIVITY_TYPE_PERMISSION = 40;

// Permisos - ocupaciones
export const SHOW_OCCUPATIONS_PERMISSION = 41;
export const CREATE_OCCUPATION_PERMISSION = 42;
export const UPDATE_OCCUPATION_PERMISSION = 43;
export const DELETE_OCCUPATION_PERMISSION = 44;

// Permisos - price range
export const SHOW_PRICE_RANGES_PERMISSION = 45;
export const CREATE_PRICE_RANGE_PERMISSION = 46;
export const UPDATE_PRICE_RANGE_PERMISSION = 47;
export const DELETE_PRICE_RANGE_PERMISSION = 48;

// Permisos - imágenes publicitarias
export const SHOW_ADVERSITING_IMAGES_PERMISSION = 49;
export const CREATE_ADVERSITING_IMAGE_PERMISSION = 50;
export const UPDATE_ADVERSITING_IMAGE_PERMISSION = 51;
export const DELETE_ADVERSITING_IMAGE_PERMISSION = 52;

// Permisos - módulos
export const SHOW_MODULES_PERMISSION = 53;
export const CREATE_MODULE_PERMISSION = 54;
export const UPDATE_MODULE_PERMISSION = 55;
export const DELETE_MODULE_PERMISSION = 56;

// Permisos - auditoría de sistemas
export const SHOW_SYSTEM_AUDITORIES_PERMISSION = 57;
export const CREATE_SYSTEM_AUDITORY_PERMISSION = 58;
export const UPDATE_SYSTEM_AUDITORY_PERMISSION = 59;
export const DELETE_SYSTEM_AUDITORY_PERMISSION = 60;

// Permisos - errores
export const SHOW_MISTAKES_PERMISSION = 61;
export const CREATE_MISTAKE_PERMISSION = 61;
export const UPDATE_MISTAKE_PERMISSION = 61;
export const DELETE_MISTAKE_PERMISSION = 61;

// Permisos - configuraciones generales
export const SHOW_GENERAL_SETTINGS_PERMISSION = 65;
export const CREATE_GENERAL_SETTING_PERMISSION = 65;
export const UPDATE_GENERAL_SETTING_PERMISSION = 67;
export const DELETE_GENERAL_SETTING_PERMISSION = 68;

// Permisos - proyectos
export const SHOW_PROJECTS_PERMISSION = 69;
export const CREATE_PROJECT_PERMISSION = 70;
export const UPDATE_PROJECT_PERMISSION = 71;
export const DELETE_PROJECT_PERMISSION = 72;
export const SHOW_PROJECTS_LIST_PERMISSION = 160;
export const SEPERATED_UNIT_CHANGE_PERMISSION = 159;

// Permisos - control de competencias
export const SHOW_POWER_CONTROLS_PERMISSION = 73;
export const CREATE_POWER_CONTROL_PERMISSION = 74;
export const UPDATE_POWER_CONTROL_PERMISSION = 75;
export const DELETE_POWER_CONTROL_PERMISSION = 76;

// Permisos - clientes
export const SHOW_CUSTOMERS_PERMISSION = 77;
export const CREATE_CUSTOMER_PERMISSION = 78;
export const UPDATE_CUSTOMER_PERMISSION = 79;
export const DELETE_CUSTOMER_PERMISSION = 80;
export const REASSIGN_ADVISOR_CUSTOMER_PERMISSION = 81;

// Permisos - seguimiento de clientes
export const SHOW_CUSTOMERS_TRACKING_PERMISSION = 82;
export const CREATE_CUSTOMER_TRACKING_PERMISSION = 83;
export const UPDATE_CUSTOMER_TRACKING_PERMISSION = 84;
export const DELETE_CUSTOMER_TRACKING_PERMISSION = 85;

// Permisos - cotizaciones
export const SHOW_QUOTATIONS_PERMISSION = 86;
export const CREATE_QUOTATION_PERMISSION = 92;
export const UPDATE_QUOTATION_PERMISSION = 91;
export const DELETE_QUOTATION_PERMISSION = 89;///descar,,,........
export const SEPERATED_UNIT_QUOTATION_PERMISSION = 3;
export const SEND_EMAIL_QUOTATION_PERMISSION = 90;
export const LEGALIZE_SALE_QUOTATION_PERMISSION = 88;
export const PRINT_QUOTATION_PERMISSION = 87;

// Permisos - nueva cotización
export const SHOW_NEW_QUOTATIONS_PERMISSION = 93;

// Permisos - ventas realizadas
export const SHOW_SALES_MADE_PERMISSION = 102;
export const CREATE_SALE_MADE_PERMISSION = 103;
export const UPDATE_SALE_MADE_PERMISSION = 104;
export const DELETE_SALE_MADE_PERMISSION = 446;///mmmmm
export const PRINT_SALE_MADE_PERMISSION = 101;
export const REASSIGN_ADVISOR_SALE_MADE_PERMISSION = 98;
export const ASSIGN_RESPONSIBLE_SALE_MADE_PERMISSION = 99;
export const LEGALIZE_DOCUMENTS_SALE_MADE_PERMISSION = 97;
export const REMAINING_WAY_TO_PAY_SALE_MADE_PERMISSION = 100;
export const DEED_SALE_MADE_PERMISSION = 96;
export const CHANGE_CUSTOMER_PERMISSION = 95;
export const EXCHANGE_MANAGEMENT_PERMISSION = 94;
export const DESIST_SALE_MADE_PERMISSION = 105;

// Permisos - solicitudes de reforma
export const SHOW_REFORM_REQUESTS_PERMISSION = 106;
export const CREATE_REFORM_REQUEST_PERMISSION = 111;
export const UPDATE_REFORM_REQUEST_PERMISSION = 110;
export const DELETE_REFORM_REQUEST_PERMISSION = 112;
export const CUSTOMER_MANAGEMENT_REFORM_REQUEST_PERMISSION = 109;
export const TECHNICAL_MANAGEMENT_REFORM_REQUEST_PERMISSION = 108;
export const CUSTOMER_REQUEST_REFORM_REQUEST_PERMISSION = 107;


// Permisos - postventas
export const SHOW_AFTER_SALES_PERMISSION = 113;
export const CREATE_AFTER_SALE_PERMISSION = 114;
export const UPDATE_AFTER_SALE_PERMISSION = 115;
export const DELETE_AFTER_SALE_PERMISSION = 116;

// Permisos - copones
export const SHOW_COUPONS_PERMISSION = 117;
export const CREATE_COUPON_PERMISSION = 118;
export const UPDATE_COUPON_PERMISSION = 119;
export const DELETE_COUPON_PERMISSION = 120;
export const SEND_COUPON_PERMISSION = 122;
export const PRINT_COUPON_PERMISSION = 121;

// Permisos - verificacion de comisiones
export const SHOW_COMMISSION_VERIFICATIONS_PERMISSION = 158;
export const CREATE_COMMISSION_VERIFICATION_PERMISSION = 158;
export const UPDATE_COMMISSION_VERIFICATION_PERMISSION = 158;
export const DELETE_COMMISSION_VERIFICATION_PERMISSION = 158;

// Permisos - recaudos directos
export const SHOW_DIRECT_COLLECTIONS_PERMISSION = 123;
export const CREATE_DIRECT_COLLECTION_PERMISSION = 124;
export const UPDATE_DIRECT_COLLECTION_PERMISSION = 125;
export const DELETE_DIRECT_COLLECTION_PERMISSION = 126;
export const VERIFY_DIRECT_COLLECTION_PERMISSION = 127;
export const SEND_2_ACCOUNTANCY_COLLECTION_PERMISSION = 128;

// Permisos - recaudos de fiducias
export const SHOW_TRUST_FUNDS_PERMISSION = 129;
export const CREATE_TRUST_FUND_PERMISSION = 130;
export const UPDATE_TRUST_FUND_PERMISSION = 131;
export const DELETE_TRUST_FUND_PERMISSION = 132;
export const SHOW_LAST_TRUST_FUND_PERMISSION = 129;
export const DOWNLOAD_FORMAT_TRUST_FUND_PERMISSION = 129;


// Permisos - reportes
export const SHOW_SALES_REPORT_PERMISSION = 135;
export const SHOW_SALES_PLAN_REPORT_PERMISSION = 136;
export const SHOW_COMPETITION_REPORT_PERMISSION = 137;
export const SHOW_REFORM_REPORT_PERMISSION = 138;
export const SHOW_ACTIVITY_TRACKING_REPORT_PERMISSION = 139;
export const SHOW_POTENTIAL_CUSTOMER_REPORT_PERMISSION = 140;
export const SHOW_ACCOUNT_STATUS_REPORT_PERMISSION = 141;
export const SHOW_LEGALIZATION_AND_DEED_REPORT_PERMISSION = 142;
export const SHOW_COLLECTION_FLOW_REPORT_PERMISSION = 143;
export const SHOW_PORTFOLIO_MONITORING_REPORT_PERMISSION = 144;
export const SHOW_COMMISSION_REPORT_PERMISSION = 145;
export const SHOW_GENERAL_COMMERCIAL_MANAGEMENT_REPORT_PERMISSION = 146;
export const SHOW_ADVISORY_MANAGEMENT_REPORT_PERMISSION = 147;
export const SHOW_ADVERTISING_EFFECTIVENESS_REPORT_PERMISSION = 148;
export const SHOW_BUYERS_DATABASE_REPORT_PERMISSION = 149;
export const SHOW_POTENTIAL_CUSTOMER_DATABASE_REPORT_PERMISSION = 150;
export const SHOW_PROJECT_MANAGEMENT_REPORT_PERMISSION = 151;
export const SHOW_AUDIT_REPORT_PERMISSION = 152;
export const SHOW_COMMISSION_PAYMENTS_REPORT_PERMISSION = 153;
export const SHOW_COLLECTION_MANAGEMENT_PERMISSION = 2;

//-- Modulos - Submodulos

// Submodulos - Config
export const PROFILES_SUBMODULE = 8;
export const USERS_SUBMODULE = 9;
export const ADVISERS_SUBMODULE = 10;
export const GENERAL_ACTIVITIES_SUBMODULE = 11;
export const AFFILIATES_SUBMODULE = 12;
export const ATTENTION_PLACES_SUBMODULE = 13;
export const CHANNEL_SUBMODULE = 14;
export const RECORD_TYPE_SUBMODULE = 15;
export const ACTIVITY_TYPE_SUBMODULE = 16;
export const OCCUPATION_SUBMODULE = 17;
export const PRICE_RANGE_SUBMODULE = 18;
export const ADVERTISIN_IMAGE_SUBMODULE = 19;
export const MODULES_SUBMODULE = 20;
export const SYSTEM_AUDIT_SUBMODULE = 21;
export const MISTAKES_SUBMODULE = 22;
export const GENERAL_SETTING_SUBMODULE = 23;
export const PROJECTS_CLASSIFICATIONS_SUBMODULE = 162;
export const CONSIGNMENT_CONCEPT_SUBMODULE = 161;



//Submodulos - Proyectos
export const PROJECTS_SUBMODULE = 24;
export const POWER_CONTROL_SUBMODULE = 25;

//Submodulos - Clientes
export const CUSTOMER_SUBMODULE = 26;
export const CUSTOMER_TRACKING_SUBMODULE = 27;

//Submodulos - Ventas
export const QUOTATION_SUBMODULE = 28;
export const NEW_QUOTE_SUBMODULE = 29;
export const SALES_MADE_SUBMODULE = 30;
export const REFORM_REQUEST_SUBMODULE = 31;
export const AFTER_SALE_SUBMODULE = 32;
export const COUPONS_SUBMODULE = 33;
export const COMISSION_VERIFICATION_SUBMODULE = 34;

//Submodulos - Recaudos
export const DIRECT_COLLECTION_SUBMODULE = 34;
export const TRUST_FUND_SUBMODULE = 35;

//Submodulos - Reports
export const SALE_REPORT_SUBMODULE = 36;
export const SALE_PLAN_SUBMODULE = 37;
export const COMPETITION_REPORT_SUBMODULE = 38;
export const REFORM_REPORT_SUBMODULE = 39;
export const ACTIVITY_TRACKING_SUBMODULE = 40;
export const POTENTIAL_CUSTOMER_SUBMODULE = 41;
export const ACCOUNT_STATUS_SUBMODULE = 42;
export const LEGALIZATION_DEED_REPORT_SUBMODULE = 43;
export const COLLECTION_FLOW_REPORT_SUBMODULE = 44;
export const PORTFOLIO_MONITORING_REPORT_SUBMODULE = 45;
export const COMMITTE_REPORT_SUBMODULE = 46;
export const GENERAL_COMMERCIAL_MANAGEMENT_REPORT_SUBMODULE = 47;
export const ADVISORY_MANAGEMENT_REPORT_SUBMODULE = 48;
export const ADVERTISING_EFFECTIVENESS_REPORT_SUBMODULE = 49;
export const BUYERS_DATABASE_SUBMODULE = 50;
export const POTENTIAL_CLIENTS_DATABASE_SUBMODULE = 51;
export const PROJECT_MANAGEMENT_REPORT_SUBMODULE = 52;
export const AUDIT_REPORT_SUBMODULE = 53;
export const PROCEEDINGS_SUBMODULE = 54;

export const DASHBOAR_LEGALIZATION_STATUS = 155;
export const DASHBOAR_CUSTOMER_TRACKING=156;
export const DASHBOAR_GENERAL_ACTIVITY_TRACKING=157;

// Dashboar route
export const DEFAULT_ROUTE = "/";
